inversePairs:inverse_pair_2.cpp util.cpp
	g++ inverse_pair_2.cpp util.cpp -o inversePairs

demo:inverse_pair_demo.cpp util.cpp
	g++ inverse_pair_demo.cpp util.cpp -o demo

clean:
	rm -rf a.out inversePairs
